# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - CodeChallenge

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build Web App
        run: dotnet build CodingChallengeApp.Web/CodingChallengeApp.Web.csproj --configuration Release

      - name: Build API App
        run: dotnet build CodingChallengeApp.Api/CodingChallengeApp.Api.csproj --configuration Release

      - name: Publish Web App
        run: dotnet publish CodingChallengeApp.Web/CodingChallengeApp.Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/webapp

      - name: Publish API App
        run: dotnet publish CodingChallengeApp.Api/CodingChallengeApp.Api.csproj -c Release -o ${{env.DOTNET_ROOT}}/apiapp

      - name: Upload Web App artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-app
          path: ${{env.DOTNET_ROOT}}/webapp

      - name: Upload API App artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-app
          path: ${{env.DOTNET_ROOT}}/apiapp

  deploy-web:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: web-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_638B82BEE7E241EBACC43F878305E135 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AF1E7BCFBC584DA7A6FBC149BD95235F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_933EE2CE9BE140E2BFA2895E816F5D8C }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CodeChallenge'
          slot-name: 'Production'
          package: .

  deploy-api:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-api.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_638B82BEE7E241EBACC43F878305E135 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AF1E7BCFBC584DA7A6FBC149BD95235F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_933EE2CE9BE140E2BFA2895E816F5D8C }}

      - name: Deploy to Azure Web App (API)
        id: deploy-to-api
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CodeChallenge-API'
          slot-name: 'Production'
          package: .
          